webapp/profile/models.py
from db import Base
from sqlalchemy import (BigInteger, Boolean, Column, Date, DateTime,
                        ForeignKey, Integer, String, Text, Time,
                        UniqueConstraint)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    telegram_id = Column(BigInteger, nullable=False, unique=True, index=True)
    telegram = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    phone = Column(String, index=True)
    description = Column(Text, nullable=False)
    gmt = Column(Time, nullable=False)
    gmt_sign = Column(String, nullable=False)
    mentors_blocked = Column(Boolean, default=False)


class Role(Base):
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=False)
    active = Column(Boolean, nullable=False)


class UserRole(Base):
    __tablename__ = "users_roles"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    role_id = Column(Integer, ForeignKey("roles.id"))

    __table_args__ = (
        UniqueConstraint(
            'user_id', 'role_id', name='unique_UserRole'),
                        )


class Specialization(Base):
    __tablename__ = "specializations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)


class UserSpecialization(Base):
    __tablename__ = "users_specializations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    specialization_id = Column(Integer, ForeignKey("specializations.id"))

    __table_args__ = (
        UniqueConstraint(
            'user_id', 'specialization_id', name='unique_UserSpecialization'),
                        )

webapp/mentors/views.py
from flask import (Blueprint, render_template, request, redirect, url_for)
from webapp.get_data import (get_all_specializations, get_date_set,
                             get_time_set, get_list_dict_mentors,
                             get_user_data, parcel_date_str, parcel_time_str,
                             search_mentors)
from webapp.update_data import create_event
from webapp import settings_conf

mentors_blueprint = Blueprint('mentors', __name__, url_prefix='/mentors')
homepage_title = "MentorMatch Calendar"


@mentors_blueprint.route("/", methods=["POST"])
def mentors():
    title = "Mentors"
    telegram = request.form.get("telegram")
    telegram_id = int(request.form.get("telegram_id"))
    search_result_str = request.form.get("search_result")
    search_query_str = request.form.get("search_query")
    search_result = get_list_dict_mentors(search_result_str)
    if search_query_str and not search_result:
        search_result = "empty"
    user_data = get_user_data(telegram_id)
    role_id = set()
    blocked = False
    name = None
    if user_data:
        role_id = user_data.get("role_id")
        blocked = user_data.get("mentors_blocked")
        name = user_data.get("name")
    return render_template("mentors.html", blocked=blocked,
                           homepage=homepage_title,
                           mentor_role_id=settings_conf.MENTOR_ROLE_ID,
                           name=name, page_title=title, role_id=role_id,
                           search_result=search_result,
                           search_query=search_query_str,
                           telegram=telegram, telegram_id=telegram_id)


@mentors_blueprint.route("/mentors_search")
def mentors_search():
    telegram = request.args.get("telegram")
    telegram_id = int(request.args.get("telegram_id"))
    action = request.args.get("action")
    create_event = request.args.get("create_event")
    search_query = request.args.get("search-mentors")
    if action == "registration":
        title = "Mentors registration form"
        all_specializations = get_all_specializations()
        return render_template("mentors_registration.html",
                               all_specializations=all_specializations,
                               homepage=homepage_title, page_title=title,
                               role_id=settings_conf.MENTOR_ROLE_ID,
                               telegram=telegram, telegram_id=telegram_id)
    elif action == "request_to_admin":
        pass
        return redirect(url_for("homepage", telegram=telegram,
                                telegram_id=telegram_id))
    elif create_event:
        return render_template("post_redirect.html",
                               mentor_telegram_id=create_event,
                               telegram=telegram, telegram_id=telegram_id)
    elif not search_query:
        return render_template("post_redirect.html",
                               search_result=" ",
                               search_query=" ",
                               telegram=telegram,
                               telegram_id=telegram_id
                               )
    if action == "search":
        search_result = search_mentors(search_query, telegram_id,
                                       settings_conf.MENTOR_ROLE_ID)
        return render_template("post_redirect.html",
                               search_result=search_result,
                               search_query=search_query,
                               telegram=telegram, telegram_id=telegram_id)
    return redirect(url_for("homepage", telegram=telegram,
                            telegram_id=telegram_id))


@mentors_blueprint.route("/mentors_search/book_time", methods=["POST"])
def book_time():
    title = "Mentor booking"
    telegram = request.form.get("telegram")
    telegram_id = int(request.form.get("telegram_id"))
    gmt = request.form.get("gmt")
    gmt_sign = request.form.get("gmt_sign")
    user_data = get_user_data(telegram_id)
    if user_data:
        role_id = user_data.get("role_id")
        name = user_data.get("name")
    else:
        role_id = set()
        name = None
    mentor_telegram_id = request.form.get("mentor_telegram_id")
    date = request.form.get("date")
    chose_date_val = request.form.get("chose_date")
    if date and not chose_date_val:
        date = parcel_date_str(date)
    time = request.form.get("time")
    chose_time = request.form.get("chose_time")
    if time and not chose_time:
        time = parcel_time_str(time)
    mentor_data = get_user_data(mentor_telegram_id)
    return render_template("booking_mentor.html",
                           chose_date_val=chose_date_val,
                           chose_time=chose_time, date=date, gmt=gmt,
                           gmt_sign=gmt_sign, homepage=homepage_title,
                           mentor_data=mentor_data,
                           mentor_role_id=settings_conf.MENTOR_ROLE_ID,
                           name=name, page_title=title, role_id=role_id,
                           telegram=telegram, telegram_id=telegram_id,
                           time=time)


@mentors_blueprint.route("/book_time/find_timslots")
def find_timslots():
    telegram = request.args.get("telegram")
    telegram_id = int(request.args.get("telegram_id"))
    chose = request.args.get("chose")
    gmt = request.args.get("gmt")
    gmt_sign = request.args.get("gmt_sign")
    mentor_telegram_id = request.args.get("mentor_telegram_id")
    chose_date_val = request.args.get("chose_date") or ""
    chose_time_ids = request.args.getlist("chose_time") or ""
    create_booking = request.args.get("create_booking") or ""
    description = request.args.get("description")
    date = ""
    time = ""
    if chose == "chose_gmt" or chose == "edit_date":
        date = get_date_set(mentor_telegram_id, gmt, gmt_sign) or ""
        chose_date_val = ""
    elif chose == "chose_date" or chose == "edit_time":
        time = (get_time_set(mentor_telegram_id, gmt, gmt_sign,
                             chose_date_val)
                or "")
        chose_time_ids = ""
    elif create_booking:
        result_creation = create_event(telegram_id, telegram, description,
                                       chose_time_ids)
        if result_creation:
            return redirect(url_for("calendar.my_calendar",
                                    successful_create=True,
                                    telegram=telegram,
                                    telegram_id=telegram_id))
        else:
            return redirect(url_for("calendar.my_calendar", error_create=True,
                                    telegram=telegram,
                                    telegram_id=telegram_id))
        
    return render_template("post_redirect.html",
                           chose_date_val=chose_date_val,
                           chose_time=chose_time_ids,
                           date=date, gmt=gmt, gmt_sign=gmt_sign,
                           mentor_telegram_id=mentor_telegram_id,
                           telegram=telegram, telegram_id=telegram_id,
                           time=time)

webapp/profile/views.py
from flask import (Blueprint, render_template, request, redirect, url_for)
from ..get_data import (get_user_data, generate_time_list)
from ..update_data import (change_data, check_username_and_update,
                           save_timeslots)
from webapp import settings_conf
from webapp.update_data import save_profile

profile_blueprint = Blueprint('profile', __name__, url_prefix='/my_profile')
homepage_title = "MentorMatch Calendar"


@profile_blueprint.route("/")
def my_profile():
    title = "My profile"
    telegram = request.args.get("telegram")
    telegram_id = int(request.args.get("telegram_id"))
    check_username_and_update(telegram, telegram_id)
    editing = request.args.get("editing", default=False, type=bool)
    user_db = get_user_data(telegram_id)
    role_id = set()
    if not user_db:
        return redirect(url_for("homepage", telegram=telegram,
                                telegram_id=telegram_id))
    name = user_db.get("name")
    role_id = user_db.get("role_id")
    return render_template("profile.html", editing=editing,
                           homepage=homepage_title,
                           mentor_role_id=settings_conf.MENTOR_ROLE_ID,
                           name=name, page_title=title, role_id=role_id,
                           telegram=telegram, telegram_id=telegram_id,
                           user_data=user_db)


@profile_blueprint.route("/actions", methods=["POST"])
def actions():
    request_form = request.form
    telegram = request_form.get("telegram")
    telegram_id = int(request_form.get("telegram_id"))
    action = request_form.get("action")
    if action == "edit":
        return redirect(url_for("profile.my_profile", editing=True,
                                telegram=telegram, telegram_id=telegram_id))
    elif action == "cancel":
        return redirect(url_for("profile.my_profile", telegram=telegram,
                                telegram_id=telegram_id))
    elif action == "submit":
        change_data(request_form)
    elif action == "create" or request_form.get("create_timeslot"):
        user_db = get_user_data(telegram_id)
        if not user_db:
            return redirect(url_for("profile.my_profile", telegram=telegram,
                                    telegram_id=telegram_id))
        title = "Time slots"
        successful_save = False
        mistake_save = False
        time_list = []
        name = user_db.get("name")
        role_id = user_db.get("role_id")
        if request_form.get("create_timeslot"):
            save = save_timeslots(request.form, user_db)
            if not save:
                mistake_save = True
            else:
                successful_save = True
        else:
            time_list = generate_time_list(settings_conf.START_TIME_SLOTS,
                                           settings_conf.END_TIME_SLOTS,
                                           settings_conf.INTERVAL_MINUTES)

        return render_template("timeslots.html", page_title=title,
                               telegram=telegram, telegram_id=telegram_id,
                               homepage=homepage_title, user_db=user_db,
                               time_list=time_list, name=name,
                               successful_save=successful_save,
                               mistake_save=mistake_save,
                               role_id=role_id,
                               mentor_role_id=settings_conf.MENTOR_ROLE_ID
                               )
    return redirect(url_for("profile.my_profile", telegram=telegram,
                            telegram_id=telegram_id))


@profile_blueprint.route("/mentors/mentors_registration", methods=["POST"])
def create_profile():
    telegram_id = int(request.form.get("telegram_id"))
    telegram = request.form.get("telegram")
    mentor_role_id = int(request.form.get("role_id"))
    save_profile(request.form)
    user_db = get_user_data(telegram_id)
    if user_db:
        role_id = user_db.get("role_id")
        if mentor_role_id in role_id:
            return redirect(url_for("homepage", mistake_creation="",
                                    successful_creation=True,
                                    telegram=telegram,
                                    telegram_id=telegram_id))
    return redirect(url_for("homepage", mistake_creation=True,
                            successful_creation="", telegram=telegram,
                            telegram_id=telegram_id))

webapp/templates/booking_mentor.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CDN via jsDelivr -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- for icons -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

        <title>{{ page_title }}</title>
        <style>
            .profile-link {
                display: inline-block; 
                text-align: center;
                margin: 10px;
                text-decoration: none;
                color: #212529;
            }
            .profile-link:hover {
                color: #0d6efd;
                text-decoration: underline;
            }
            .profile-img {
                width: 80px;
                height: 80px;
                border-radius: 50%;
                display: block; /* Убедитесь, что изображение ведет себя как блок */
                margin: 0 auto;
            }
            body {
                background-image:  url("{{ url_for('static', filename='images/mentors.jpg') }}");
                background-size: cover;
                background-position: center center;
                background-attachment: fixed;
                margin: 0;
                height: 100vh; /* Занимает всю высоту экрана */
            }
            .card-header{
                padding-left: 20px;
                padding-bottom: 10px;
            }
            .form-style{
                padding-left: 10px;
                padding-bottom: 10px;
            }

        </style>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="nav nav-pills nav-fill ps-3">
                <a href="{{  url_for('homepage', telegram=telegram, telegram_id=telegram_id)  }}" class="navbar-brand" >{{ homepage }}</a>
            </ul>
            {% if mentor_role_id in role_id %}
                <h3 class="text-end ms-auto m-2">Hi, {{ name }}</h3>
            {% endif %}
        </nav>

        <div class="card-header">
            <u><h4>{{ page_title }}</h4></u>
        </div>
        <form class="form-style" action="{{ url_for('mentors.find_timslots') }}" method="GET">
            <input type="hidden" name="telegram_id" value="{{ telegram_id }}">
            <input type="hidden" name="telegram" value="{{ telegram }}">
            <h5 class="ms-3">You chose a mentor - {{ mentor_data.telegram }}:</h5>
            <div class="text-danger-emphasis ms-3">if it's incorrect - try again or write to admin.</div>
            <input name="mentor_telegram_id" class="form-control" type="text" value="{{ mentor_data.telegram_id }}" hidden>
            <input name="mentor_id" class="form-control" type="text" value="{{ mentor_data.id }}" hidden>
            
            <div class="ms-3">Your gmt:</div>
            <div class="d-flex align-items-center m-2 mt-0">
                <select id="gmt_sign" name="gmt_sign" class="form-select mt-0" style="width: auto;">
                    <option value="{{ gmt_sign }}" disabled selected> {% if gmt_sign %} {{ gmt_sign }} {% else %} choose {% endif %}</option>
                    <option value="+">+</option>
                    <option value="-">-</option>
                </select>
                <input type="time" id="gmt" value="{{ gmt }}" name="gmt" style="width: auto;" class="form-control m-2">
                <input id="gmt_sign" value="{{ gmt_sign }}" name="gmt_sign" hidden>
            </div> 
            <button id="submit_gmt" class="btn btn-primary ms-3" type="submit" name="chose" value="chose_gmt" disabled>Submit gmt</button>
            
            <div id="date_form" hidden>
                {% if not chose_date_val and not date %}
                    <div class="text-danger ms-3">This mentor does not have <br>an available date now. <br>You should check it later</div>
                {% else %}
                    <label class="form-style" for="time_slot">Choose an available date:</label>
                    <div class="d-flex align-items-center">
                        <select id="chose_date" name="chose_date" class="form-select m-2" style="width: auto;">
                            <option value="{{ chose_date_val }}" disabled selected> 
                                {% if chose_date_val %} {{ chose_date_val }} {% else %} date: {% endif %}
                            </option>
                            {% for el in date %}
                                <option value="{{ el }}">{{ el }}</option>
                            {% endfor %}
                        </select>
                        <input id="chose_date" value="{{ chose_date_val }}" name="chose_date" hidden>
                        <button id="submit_date" class="btn btn-primary ms-3" name="chose" type="submit" value="chose_date" disabled>Choose date</button>
                        <button id="edit_date" class="btn btn-success ms-3" name="chose" type="submit" value="edit_date" hidden>Edit date</button>
                    </div>
                {% endif %}
            </div>

            <div id="time_form" hidden>
                <label class="form-style" for="chose_time">Choose an available time:</label><br>
                {% for el in time %}
                    <div class="form-check ms-3">
                        <input id="chose_time" name="chose_time" class="form-check-input" type="checkbox" value="{{ el[0] }}">
                        <label class="form-check-label" for="flexCheck">  
                            {{ el[1] }} 
                        </label> 
                    </div> 
                {% endfor %}
                <button id="submit_time" name="submit_time" class="btn btn-primary ms-3 mt-2" type="button" disabled>Choose time</button>
                <button id="edit_time" class="btn btn-success ms-3 mt-2" name="chose" type="submit" value="edit_time" hidden>Edit time</button>
            </div>
            
            <div id="description_form" hidden>
                <label class="form-style mt-2" for="description">Your request is:</label><br>
                <textarea id="description" name="description" 
                       class="form-control form-control-sm input-stile" 
                       type="text" style="width: auto;"></textarea>
                <button id="create_booking" name="create_booking" value="booking" 
                        type="submit" class="btn btn-primary ms-3 mt-2" disabled>Complete booking</button> 
            </div>

        </form>

        <script>
            // .document is a built-in JavaScript object that represents the HTML document loaded in the browser. 
            // It allows you to access and interact with elements on the page.
            function openForm () {
                const gmtsign = document.getElementById('gmt_sign');
                const gmt = document.getElementById('gmt');
                const dateForm = document.getElementById('date_form');
                const buttonSubmitGMT = document.getElementById('submit_gmt');
                const chosedate = document.getElementById('chose_date');
                const buttonsubmitDate = document.getElementById('submit_date');
                const buttoneditDate = document.getElementById('edit_date')
                const timeForm = document.getElementById('time_form')
                if (gmtsign.value && gmt.value) {
                    dateForm.removeAttribute('hidden');
                    buttonSubmitGMT.setAttribute('hidden', true);
                    gmtsign.style.pointerEvents = "none";
                    gmt.style.pointerEvents = "none";
                }
                if (chosedate.value) {
                    buttoneditDate.removeAttribute('hidden');
                    buttonsubmitDate.setAttribute('hidden', true);
                    timeForm.removeAttribute('hidden')
                }

                
                // else{
                //     dateform.setAttribute('hidden', true);
                //     buttonSubmitGMT.removeAttribute('hidden');
                //     gmtsign.style.pointerEvents = "auto";
                //     gmt.style.pointerEvents = "auto";
                //     buttonsubmitDate.removeAttribute('hidden');
                //     buttoneditDate.setAttribute('hidden', true);
                // }
                const checkboxes = document.querySelectorAll('input[name="chose_time"]');
                checkboxes.forEach(checkbox => {
                    checkbox.addEventListener("change", openSubmitTime);
                });
            }

            function openSubmitGMT() {
                const gmtsignValue = document.getElementById('gmt_sign').value;
                const gmtValue = document.getElementById('gmt').value;
                const buttonSubmitGMT = document.getElementById('submit_gmt');
                if (gmtsignValue && gmtValue) {
                    buttonSubmitGMT.removeAttribute('disabled');
                } else {
                    buttonSubmitGMT.setAttribute('disabled', true);
                }
            }

            function openChooseDate(){
                const choseDate = document.getElementById('chose_date').value;
                const buttonChooseDate = document.getElementById('submit_date');
                if (choseDate) {
                    buttonChooseDate.removeAttribute('disabled');
                }else {
                    buttonChooseDate.setAttribute('disabled', true);
                }
            }

            function openSubmitTime(){
                const checkboxChoseTime = document.querySelectorAll('input[name="chose_time"]:checked');
                const buttonChooseTime = document.getElementById('submit_time');
                if (checkboxChoseTime.length > 0) {
                    buttonChooseTime.removeAttribute('disabled');
                }else {
                    buttonChooseTime.setAttribute('disabled', true);
                }
            }

            function openDescriptionForm() {
                const buttonChooseTime = document.getElementById('submit_time');
                const descriptionForm = document.getElementById('description_form')
                const buttoneditTime = document.getElementById('edit_time')
                const checkboxChoseTime = document.querySelectorAll('input[name="chose_time"]');

                if (buttonChooseTime && buttonChooseTime.disabled === false) {
                    descriptionForm.removeAttribute('hidden');
                    buttonChooseTime.setAttribute('hidden', true);
                    buttoneditTime.removeAttribute('hidden');
                    checkboxChoseTime.forEach(checkbox => {
                        checkbox.style.pointerEvents = "none";
                    });
                }else {
                    descriptionForm.setAttribute('hidden', true);
                    buttonChooseTime.removeAttribute('hidden');
                    buttoneditTime.setAttribute('hidden', true);
                    checkboxChoseTime.forEach(checkbox => {
                        checkbox.style.pointerEvents = "auto";
                    });
                }
            }

            function openBookingButtom(){
                const descriptionI = document.getElementById('description');
                const create_bookingButtom = document.getElementById('create_booking');
                if (descriptionI.value.trim() !== '') {
                    create_bookingButtom.removeAttribute('disabled');
                }else {
                    create_bookingButtom.setAttribute('disabled', true);
                }
            }

            document.addEventListener('DOMContentLoaded', openForm);
            document.getElementById('gmt_sign').addEventListener('change', openSubmitGMT);
            document.getElementById('gmt').addEventListener('input', openSubmitGMT);
            document.getElementById('chose_date').addEventListener('change', openChooseDate);
            document.getElementById('submit_time').addEventListener('click', openDescriptionForm);
            document.getElementById('description').addEventListener('input', openBookingButtom);

        </script>
        </body>
</html>

webapp/templates/post_redirect.html
<!DOCTYPE html>
<html>
<body>
    <form id="post_form_book_time" action="{{ url_for('mentors.book_time') }}" method="POST">
        <input type="hidden" name="telegram" value="{{ telegram }}">
        <input type="hidden" name="telegram_id" value="{{ telegram_id }}">
        <input type="hidden" name="gmt" value="{{ gmt }}">
        <input type="hidden" name="mentor_telegram_id" value="{{ mentor_telegram_id }}">
        <input type="hidden" name="gmt_sign" value="{{ gmt_sign }}">
        <input type="hidden" name="date" value="{{ date }}">
        <input type="hidden" name="time" value="{{ time }}">
        <input type="hidden" name="chose_date" value="{{ chose_date_val }}">
        <input type="hidden" name="chose_time" value="{{ chose_time }}">
        <input type="hidden" name="successful_save" value="{{ successful_save }}">
        <input type="hidden" name="mistake_save" value="{{ mistake_save }}">
    </form>

    <form id="post_form_mentors" action="{{ url_for('mentors.mentors') }}" method="POST">
        <input type="hidden" name="telegram" value="{{ telegram }}">
        <input type="hidden" name="telegram_id" value="{{ telegram_id }}">
        <input type="hidden" name="search_result" value="{{ search_result }}">
        <input type="hidden" name="search_query" value="{{ search_query }}">

    </form>
    <script>
        let searchResult = "{{ search_result }}";
        
        if (searchResult) {
            document.getElementById("post_form_mentors").submit();
        } else {
            document.getElementById("post_form_book_time").submit();
        }
    </script>
</body>
</html>